name: webhook

on: [ push, pull_request ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        run: |
          curl ${{ secrets.WEBHOOK }} \
          -H 'Content-Type: application/json' \
          -d '
          {
            "msgtype": "markdown",
            "markdown": {
                "content": "通知\n
                 >repo: <font color=\"comment\">[${{github.repository}}](${{github.repositoryUrl}})</font>
                 >branch: <font color=\"comment\">[${{github.ref_name}}](${{github.repositoryUrl}})</font>
                 >commit id: <font color=\"comment\">[${{github.sha}}](${{github.repositoryUrl}})</font>
                 >commit message: <font color=\"comment\">[${{github.event.head_commit.message}}](${{github.repositoryUrl}})</font>"
            }
          }'
