name: webhook

on: [ push, pull_request ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        run: |
          curl ${{ secrets.WEBHOOK }} \
          -H 'Content-Type: application/json' \
          -d '
          {
            "msgtype": "markdown",
            "markdown": {
                "content": "通知\n
                 >仓库: <font color=\"comment\">${github.repository}</font>
                 >分支: <font color=\"comment\">${github.ref_name}</font>
                 >推送消息: <font color=\"comment\">${github.event.head_commit.message}</font>"
            }
          }'
