name: webhook

on: [ push, pull_request ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        run: |
          curl ${{ secrets.WEBHOOK }} \
          -H 'Content-Type: application/json' \
          -d '
          {
            "msgtype": "text",
            "text": {
              "content": "hello world"
            }
          }'
