name: webhook

on: [ push, pull_request ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=693axxx6-7aoc-4bc4-97a0-0ec2sifa5aaa' \
          -H 'Content-Type: application/json' \
          -d '
          {
            "msgtype": "text",
            "text": {
              "content": "hello world"
            }
          }'
